language: node_js
node_js:
 - "11.10.0"
services:
  - MongoDB
before_install:
  - cd application_code
  - npm i -g npm@6.7.0
install:
  - npm install
cache: 
  - npm
script:
  - npm run test
notifications:
  slack: 
	rooms:
	  - nyu-agile-software:3r6ZGUi2nSsm830plGN2IVEE#instrument_exchange
	  - nyu-agile-software:3r6ZGUi2nSsm830plGN2IVEE#travis-results
