apiVersion: v1
kind: Service
metadata:
  name: ie-service
spec:
  selector:
     app: ie-deployment
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: LoadBalancer
  sessionAffinity: ClientIP
